name: Upload website

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v2

      # Step 2: Setup Node.js with caching for pnpm
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use Node.js v18
          cache: 'pnpm' # Cache dependencies installed with pnpm

      # Step 3: Install pnpm globally
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate

      # Step 4: Install dependencies using pnpm
      - name: Install Dependencies
        run: pnpm install

      # Step 5: Build the static files
      - name: Build Static Files
        run: pnpm run build

      # Step 6: Configure AWS credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Step 7: Deploy static site to S3 bucket
      - name: Deploy Static Site to S3
        run: aws s3 sync ./build s3://fix-it-bucket --delete
